import React from "react";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/main/Navbar";
import PropTypes from "prop-types";

const poppins = localFont({
  src: "./fonts/Poppins-Regular.ttf",
  variable: "--font-poppins",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const propTypes = {
  children: PropTypes.node,
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

RootLayout.propTypes = propTypes;

export default RootLayout;
